Chore/118 fix deprecation warnings
cloudposse/terraform-aws-tfstate-backend pull request #119
Opened 2022-08-03 06:21 UTC by vanastassiou

## what
Partially resolves deprecation warnings during `terraform plan` and `terraform apply`. Uses https://github.com/nozaq/terraform-aws-remote-state-s3-backend as a model. Remaining deprecation warnings should probably be corrected in a PR to in https://github.com/cloudposse/terraform-aws-s3-bucket (referenced in the `log_storage` module code used in this module).

## why
* Avoid functionality loss when deprecated functions are dropped
* Reduce noise in `terraform plan` and `terraform apply`

## references
* Closes https://github.com/cloudposse/terraform-aws-tfstate-backend/issues/118

2022-08-03 17:11 UTC, vanastassiou commented
HI @aknysh, thanks for the review. I've pushed changes that give me a `terraform plan` with no errors on Terraform 1.2.6.

2022-08-04 16:39 UTC, vanastassiou commented
The warnings that are blocking the `terratest` job are probably due to the `s3-log-storage` module needing to be updated similarly. I'll submit a PR for that one and then notify here once that's resolved.

2022-08-30 05:38 UTC, vanastassiou commented
@joe-niland  @RothAndrew any guidance on how I should address the `context deadline exceeded` error in terratest?

2022-08-30 15:31 UTC, RothAndrew commented
Not sure, maybe just a hiccup. will try running the tests again

2022-08-30 15:31 UTC, RothAndrew commented
/test all

2022-08-30 15:41 UTC, RothAndrew commented
The terratest test passed this time, which means the failure was just AWS having a hiccup.

This looks like more than just a chore/refactor though, as it is making breaking changes to the inputs.

@aknysh, who's the right person to put this in front of to make sure this is a change we want to make? I don't have enough context on this module to give it the review it needs.

2022-08-30 17:44 UTC, nitrocode commented
/test test/readme

2022-08-30 19:40 UTC, Nuru commented
/rebuild-readme

2022-08-30 19:41 UTC, Nuru commented
/test readme

2022-08-30 19:43 UTC, Nuru commented
/test bats terratest

2022-08-31 18:25 UTC, Nuru requested changes
@vanastassiou Thank you very much for providing these proposed changes. 

While we appreciate your effort, we have additional requirements/priorities for our open source modules that we want fulfilled in any PR we are going to approve. My apologies if this is an extra burden.

First, we want to preserve backward compatibility if at all possible. Otherwise, every user of this module will have to take extra, manual steps to upgrade to the new version, whereas with backward compability the upgrade can be (and usually is) automated.

Second, as you pointed out, we want to migrate this module to use our [s3-bucket](https://github.com/cloudposse/terraform-aws-s3-bucket) module in the near future, so we want to keep any changes compatible and consistent with that so that in the future we can again avoid making breaking changes. 

Finally, we do not want to add features that are implemented in other modules, in order to keep modules as small and maintainable as is reasonable. For that reason, please point users to our [kms-key](https://github.com/cloudposse/terraform-aws-kms-key) module to create a KMS key if desired rather than add that functionality to this module.

2022-08-31 18:25 UTC, Nuru commented on variables.tf
> +}
@vanastassiou You are correct that we want to convert this module to use the [s3-bucket module](https://github.com/cloudposse/terraform-aws-s3-bucket). As already mentioned, we place a high value on avoiding breaking changes. We also want to limit the scope of modules to make them easier to understand and maintain, which is why we do not include the ability to provision a KMS key in the s3-bucket module. Please use the [kms-key](https://github.com/cloudposse/terraform-aws-kms-key) module to create and manage the KMS key.

Please copy [the KMS key arn input](https://github.com/cloudposse/terraform-aws-s3-bucket/blob/caf2af9a03f947ae51348e675146f6475ca228a3/variables.tf#L68-L72) from the s3-bucket module:

```suggestion
variable "kms_master_key_arn" {
  type        = string
  default     = ""
  description = "The AWS KMS master key ARN used for the `SSE-KMS` encryption. This can only be used when you set the value of `sse_algorithm` as `aws:kms`. The default aws/s3 AWS KMS master key is used if this element is absent while the `sse_algorithm` is `aws:kms`"
}
```

2022-08-31 18:25 UTC, Nuru commented on main.tf
> +  enable_key_rotation     = var.kms_key_enable_key_rotation
@vanastassiou You are correct that we want to convert this module to use the [s3-bucket module](https://github.com/cloudposse/terraform-aws-s3-bucket). As already mentioned, we place a high value on avoiding breaking changes. We also want to limit the scope of modules to make them easier to understand and maintain, which is why we do not include the ability to provision a KMS key in the s3-bucket module. We want users to use the [kms-key](https://github.com/cloudposse/terraform-aws-kms-key) module to create and manage the KMS key.

```suggestion
```

2022-12-27 18:37 UTC, matthewmrichter commented
Any chance this PR could get a little more attention?

2023-01-17 19:58 UTC, vanastassiou commented
@matthewmrichter thanks for pinging me -- this had fallen off my radar. I should be able to devote some time to it in the coming week.

2023-01-26 10:24 UTC, ilianvo commented on main.tf
> +  bucket = aws_s3_bucket.default[0].id
Hello Andriy is the server side encryption added to this module when I create s3 bucket with it shows deprecated arguments s3 default and wants me to use server side encryption how to use it ?

2023-04-24 16:31 UTC, closed without merging