Upgrade dynamodb label to `0.24.1`
cloudposse/terraform-aws-tfstate-backend pull request #93
Opened 2021-07-29 23:30 UTC by nitrocode

## what
* Upgrade dynamodb label to `0.24.1`

## why
* Latest version of context label

## references
N/A

2021-07-29 23:31 UTC, nitrocode commented
/test all

2021-07-30 00:27 UTC, nitrocode commented
/test all

2021-07-30 02:33 UTC, Nuru requested changes

2021-07-30 02:33 UTC, Nuru commented on main.tf
> +  attributes = compact(concat(["lock"], var.attributes))
```suggestion
  attributes =["lock"]
```

2021-07-30 05:39 UTC, nitrocode commented
/test all

2021-08-05 14:39 UTC, nitrocode commented
/test terratest

2021-08-05 14:39 UTC, nitrocode commented
Since the random id generated is passed in via the `var.attributes` in the terratest, the `lock` portion now shows up after the random id instead of before. I'd like to update the test but I fear that this update will break backwards compatibility.

What do you think @Nuru ?

2021-08-11 03:40 UTC, nitrocode commented
/test all

2021-08-18 04:00 UTC, aknysh approved these changes

2021-08-18 04:20 UTC, merged