Allow bucket and dynamodb to be optional
cloudposse/terraform-aws-tfstate-backend pull request #95
Opened 2021-07-29 23:55 UTC by nitrocode

## what
* Allow bucket and dynamodb to be optional

## why
* So the other properties of the module can be utilized without these resources created

## references
* Closes https://github.com/cloudposse/terraform-aws-tfstate-backend/issues/72

2021-07-29 23:57 UTC, nitrocode commented
/test all

2021-07-29 23:58 UTC, nitrocode commented
/test all

2021-07-30 00:21 UTC, nitrocode commented
/test all

2021-08-05 14:57 UTC, max-lobur requested changes

2021-08-05 14:57 UTC, max-lobur commented on main.tf
> +  count = local.bucket_enabled ? 1 : 0
This is later used in `data "template_file" "terraform_backend_config"`
You may want to add some compensating variable for that

2021-08-05 15:25 UTC, nitrocode commented on main.tf
> +  count = local.bucket_enabled ? 1 : 0
It uses `bucket = join("", aws_s3_bucket.default.*.id)` which compensates for it.

2021-08-05 15:30 UTC, max-lobur approved these changes

2021-08-11 03:40 UTC, merged